version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0

executors:
  node:
    docker:
      - image: cimg/node:22.14.0

commands:
  install_dependencies:
    steps:
      - run: npm ci

jobs:
  test:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Run Formatting Check
          command: npm run format:check
      - run:
          name: Run Linting
          command: npm run lint:check
      - run:
          name: Run Tests
          command: npm run test

  build-deploy:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - aws-cli/setup
      - run: cd cdk && npm install
      - run:
          name: Authenticate Docker with ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION \
              | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - run:
          name: Build and Push Image
          command: |
            docker build -t nestjs-app .
            docker tag nestjs-app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nestjs-app
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nestjs-app
      - run:
          name: Deploy with CDK
          command: |
            cd cdk
            npx cdk deploy --require-approval never

workflows:
  test-build-deploy:
    jobs:
      - test
      - build-deploy:
          requires:
            - test
